### ISSUE TITLE
Add Laravel Pushwoosh To Docs?

### ISSUE THREAD

**Issue by vinkla** [hoymultimedia/Laravel-Pushwoosh#1]
@shaders is it possible to add a link to this library in the Pushwoosh documentation? http://docs.pushwoosh.com/docs/

**Comment by vinkla** [comment]
@shaders do you think it would be okay?

**Comment by shaders** [comment]
done! http://docs.pushwoosh.com/docs/createmessage

**Comment by vinkla** [comment]
Thanks!
