### ISSUE TITLE
getting invalid argument error 

### ISSUE THREAD

**Issue by lakshmajim** [hoymultimedia/Laravel-Pushwoosh#4]
**Argument 1 passed to Gomoob\Pushwoosh\Client\Pushwoosh::createMessage() must be an instance of Gomoob\Pushwoosh\Model\Request\CreateMessageRequest, string given**

My code

```
<?php

use PushNotification;

class TestController extends Controller
{

    public function sendNotification()
    {
                $data ="hi";
	        $request = json_encode(['request' => $data]);
                Pushwoosh::createMessage($request);
                Pushwoosh::getApplication();
   }
}

```

Any one help me how to use this package to send notifications to android mobile

**Comment by vinkla** [comment]
Please see the documentation http://gomoob.github.io/php-pushwoosh/

```php
 
// Create a Pushwoosh client
$pushwoosh = Pushwoosh::create()
    ->setApplication('XXXX-XXX')
    ->setAuth('xxxxxxxx');

// Create a request for the '/createMessage' Web Service
$request = CreateMessageRequest::create()
    ->addNotification(Notification::create()->setContent('Hello Jean !'));

// Call the REST Web Service
$response = $pushwoosh->createMessage($request);

// Check if its ok
if($response->isOk()) {
    print 'Great, my message has been sent !';
} else {
    print 'Oups, the sent failed :-('; 
    print 'Status code : ' . $response->getStatusCode();
    print 'Status message : ' . $response->getStatusMessage();
}
```

**Comment by lakshmajim** [comment]
@vinkla ,hi it is PHP code and it is working fine ,
I am using push notifications with laravel.

I'm getting the following error when I written code like this
```
$request ="hi this is test";
Pushwoosh::createMessage($request);
Pushwoosh::getApplication();

```
in controller file

ERROR:**
Argument 1 passed to Gomoob\Pushwoosh\Client\Pushwoosh::createMessage() must be an instance of Gomoob\Pushwoosh\Model\Request\CreateMessageRequest, string given**

**Comment by vinkla** [comment]
The `createMessage` method can't handle a string. You have to create the request:

```php
$request = CreateMessageRequest::create()
    ->addNotification(Notification::create()->setContent('Hello Jean !'));
```

**Comment by lakshmajim** [comment]
I tried that thing ,
I added providers 
at providers array         

> Hoy\Pushwoosh\PushwooshServiceProvider::class

I added Facades 
at alias array      

>   'Pushwoosh' => Hoy\Pushwoosh\Facades\Pushwoosh::class

 
But when I’m going to create an object for CreateMessageRequest it throws an error that 

** Class App\Http\Controllers\CreateMessageRequest not found error**

**Comment by vinkla** [comment]
Yes, that is because you've to import the `CreateMessageRequest` class.

**Comment by lakshmajim** [comment]
Hi @vinkla , There are no Facades available ,How can i achieve that,as those files are loaded by composer.

**Comment by vinkla** [comment]
Did you add the facade to the `app.php` config file?

**Comment by lakshmajim** [comment]
@vinkla Yes , I have added to providers and alias array 

```
<?php

return [

    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Lakshmajim\Twilio\TwilioServiceProvider::class,
        Hoy\Pushwoosh\PushwooshServiceProvider::class,

    ],

    /*
    |--------------------------------------------------------------------------
    | Class Aliases
    |--------------------------------------------------------------------------
    |
    | This array of class aliases will be registered when this application
    | is started. However, feel free to register as many as you wish as
    | the aliases are "lazy" loaded so they don't hinder performance.
    |
    */

    'aliases' => [
        'Pushwoosh' => Hoy\Pushwoosh\Facades\Pushwoosh::class

    ],

];

```

**Comment by vinkla** [comment]
Okay, good. Please paste the code where you are trying to use the facade class.

**Comment by lakshmajim** [comment]
Hi @vinkla ,
Here is my code 
```
<?php namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Requests;
use JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;
use JWTFactory;

use Hoy\Pushwoosh\Facades\Pushwoosh;
// use Hoy\Pushwoosh\PushwooshManager;
// use Gomoob\Pushwoosh\Model\Notification;

class TestController extends Controller
{
    public function sendnotification()
    {
                 $request = CreateMessageRequest::create()
                                       ->addNotification(Notification::create()->setContent('Hello lakshmaji !'));

                Pushwoosh::createMessage($request);
                Pushwoosh::getApplication();
    }

}
```

**Comment by vinkla** [comment]
You've to import `CreateMessageRequest` and `Notification` as well.

**Comment by lakshmajim** [comment]
@vinkla ,I have commented those things in TestController.I tried importing but it is throwing error

**Comment by vinkla** [comment]
You've to import them both otherwise it wont work.

**Comment by vinkla** [comment]
In your snippet you only import the `Notification` class.
